CREATE TABLE client_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  log text NULL,
  client_username text NULL,
  CONSTRAINT client_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  type character varying NULL,
  player_id bigint NULL,
  log jsonb NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT logs_pkey PRIMARY KEY (id)
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username character varying NULL,
  email character varying NULL,
  password character varying NULL,
  security_code numeric NULL,
  phone numeric NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  money numeric NULL DEFAULT '1000'::numeric,
  role text NULL,
  client_token text NULL,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);